# auto-build: {"image_name": "sumologic/collector", "tags": ["latest", "latest-docker-sources"], "calver_prefix": "docker-sources-"}
FROM sumologic/collector:latest-no-source
MAINTAINER Sumo Logic <docker@sumologic.com>
COPY sumo-sources.json /etc/sumo-sources.json
