# auto-build: {"image_name": "sumologic/collector", "tags": ["latest-logging-driver-syslog"], "calver_prefix": "logging-driver-syslog-"}
FROM sumologic/collector:latest-no-source
MAINTAINER Sumo Logic <docker@sumologic.com>
ADD sumo-sources.json /etc/sumo-sources.json
