# auto-build: {"image_name": "sumologic/collector", "tags": ["latest-file"], "calver_prefix": "file-"}
FROM sumologic/collector:latest-no-source
MAINTAINER Sumo Logic <docker@sumologic.com>
ADD sumo*.json /etc/
